### ISSUE TITLE
Request: Search Pokemon

### ISSUE THREAD

**Issue by Maker-Mark** [myarmolinsky/Ponkemo-v2#4]
I was going through the pokemon list, and it was a bit hard to find the pokemon I was looking for (Sliggoo of course;). Is there a search bar where I can look for a pokemon?

**Comment by myarmolinsky** [comment]
You'll find that making search bar is on my To-Do list in the readme, I'm looking forward to adding it 😄

**Comment by myarmolinsky** [comment]
A search bar for searching for Pokemon in the Pokedex has been added, along with search options allowing you to search not just by name but by type, ability, egg group, and base stats too.  I have also added buttons to toggle whether Pokemon formes are shown (toggled off by default) and whether shiny sprites of Pokemon are shown (also toggled off by default).
